services:
  postgres:
    image: postgres:17.9
    container_name: gachamarket-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gachamarket
      POSTGRES_USER: gachamarket
      POSTGRES_PASSWORD: gachamarket
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
