spring:
  application:
    name: gachamarket
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: false
